### ISSUE TITLE
Could not pass event PlayerQuitEvent to DiscordX v1.1.0

### ISSUE THREAD

**Issue by pupshadow** [hwalker928/DiscordX#12]
**Plugin version**
DiscordX version 1.1.0

**Server version**
This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-602 (MC: 1.16.5)

**What happens**
LOG:  Could not pass event PlayerQuitEvent to DiscordX v1.1.0
java.util.concurrent.RejectedExecutionException: The Requester has been stopped! No new requests can be requested!
        at net.dv8tion.jda.internal.requests.Requester.request(Requester.java:105) ~[?:?]
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:189) ~[?:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:411) ~[?:?]
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:377) ~[?:?]
        at org.harrydev.discordx.Events.JoinLeaveEvent.OnPlayerLeave(JoinLeaveEvent.java:33) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor300.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-629]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:597) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1842) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:520) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:178) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1511) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Expected behavior**
To show a player quit properly to discord.

**Comment by hwalker928** [comment]
Please run /dxdebug and send the link here.

**Comment by pupshadow** [comment]
Oof sorry I got rid of it when i didnt see any response ill bring it back sometime for run and see.
