### ISSUE TITLE
Webhook causes error on first boot

### ISSUE THREAD

**Issue by hwalker928** [hwalker928/DiscordX#6]
**Plugin version**
8e47354

**Server version**
Tuinity version git-Tuinity-"cc34294" (MC: 1.16.4) 

**What happens**
First boot errors out due to invalid webhook URL

**Expected behavior**
No error

**Screenshots**
`[16:28:16 INFO]: [DiscordX] Enabling DiscordX v0.1*
[16:28:16 WARN]: [DiscordX] Please Set the bot token in the config.yml!
[16:28:16 WARN]: [DiscordX] Aborting
[16:28:16 WARN]: [DiscordX] Please Set the webhook URL in the config.yml!
[16:28:16 WARN]: [DiscordX] Aborting...
[16:28:16 ERROR]: Error occurred while enabling DiscordX v0.1 (Is it up to date?)
java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:84) ~[?:?]
        at org.harrydev.discordx.Bot.webhook.Start(webhook.java:30) ~[?:?]
        at org.harrydev.discordx.DiscordX.onEnable(DiscordX.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:938) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]`

**Additional context**
Was meant to be fixed

**Comment by hwalker928** [comment]
And to add on top of this, the plugin does not have an option to disable webhooks.

**Comment by hwalker928** [comment]
This has been sorted.
